version: '2'
services:
  db:
    build: ./db
    networks:
      - main
    ports:
      - "3306:3306"
    volumes:
      - db_data:/opt/taggernews/mysql_data
    restart: always
  web:
    build: ./web
    networks:
      - main
    volumes:
      - ./web/tagger:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  db_data:
  web:
networks:
  main: