version: '2'
services:
  db:
    build: ./db
    networks:
      - main
    ports:
      - "3306:3306"
    volumes:
      - db_data:/opt/taggernews/mysql_data
    restart: always
  web:
    build: ./web
    networks:
      - main
    volumes:
      - ./web/tagger:/usr/src/app
    ports:
      - "80:8000"
    depends_on:
      - db
  stream:
    restart: on-failure
    build: ./stream
    networks:
      - main
    volumes:
      - ./stream/stream:/usr/src/app
    depends_on:
      - db
  refresh:
     restart: on-failure
    build: ./refresh
    networks:
      - main
    volumes:
      - ./refresh/refresh:/usr/src/app
    depends_on:
      - db
volumes:
  db_data:
  web:
networks:
  main: